name: Java CI/CD with Gradle and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Display Class Info
        run: echo "Hi, I am from COSC 1209 class"

      - name: Grant execute permission to Gradle wrapper (Linux/macOS only)
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Build the JAR
        run: |
          ./gradlew clean build || ./gradlew clean build

      - name: Verify JAR file location (Cross-platform)
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            dir build\libs
          else
            ls -l build/libs
          fi

      - name: Get JAR filename (Cross-platform)
        id: get_jar
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            $jar = Get-ChildItem -Path build\libs\*.jar | Select-Object -First 1
#### Block C
